[project]
name = "informal-jobs-model"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "numpy>=2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
]
